name: Notify Telegram

on:
  push:
    branches:
      - master
  pull_request:
     branches: [ "master" ]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Telegram
        env:
          TELEGRAM_BOT_TOKEN: 7951773053:AAFSQCGVxrpOb0SUX6SSOIblEBp94nYpAII
          TELEGRAM_CHAT_ID: -1002418595945
          TELEGRAM_THREAD_ID: 3 
          COMMITTER_NAME: ${{ github.actor }}
          COMMITTER_EMAIL: ${{ github.event.pusher.email }}
        run: |
          MESSAGE="🚀 *GitHub Action Triggered!*%0ARepository: ${{ github.repository }}%0AEvent: ${{ github.event_name }}%0ACommit: ${{ github.sha }}%0ACommitter: *$COMMITTER_NAME*%0AEmail: $COMMITTER_EMAIL%0A[View on GitHub](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }})"

          curl -s -X POST "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage" \
          -d "chat_id=$TELEGRAM_CHAT_ID" \
          -d "message_thread_id=$TELEGRAM_THREAD_ID" \
          -d "text=$MESSAGE" \
          -d "parse_mode=Markdown"
